### ISSUE TITLE
Update project to support .NET 7 and upgrade related packages

### ISSUE THREAD

**Issue by chihkang** [Schentrup-Software/Automatic-Stock-Trader#39]
Hello,

I'm using the Automatic Stock Trader application, and I noticed that it currently supports .NET 5. Since .NET 7 has been released with new features and performance improvements, I would like to request an update to the project to support .NET 7.

In addition to updating the project to .NET 7, it would be helpful to upgrade the related packages and dependencies to their latest compatible versions. This update might include addressing any API changes or deprecated methods to ensure the project continues to work smoothly with the latest technology.

Here's a high-level overview of the changes that would be great to see:

1. Update the target framework to .NET 7 in the project file(s).
2. Upgrade NuGet packages and other dependencies to their latest compatible versions.
3. Review and update any deprecated API calls or methods, as needed.
4. Verify that the application continues to function correctly after the updates, including running tests and ensuring compatibility with the new framework and packages.
5. Update the documentation to reflect the new .NET version and any other relevant changes.

I believe these updates would help improve the application's performance, maintainability, and compatibility with the latest .NET technologies.

Thank you for considering this request!

**Comment by joeySchentrup** [comment]
Made a commit to close this issue. I was not able to fully test it as my account is not in good standing. Let me know if you run into any issues.
